
services:

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: >
        bash -c '
          rabbitmq-diagnostics -q ping &&
          nc -z localhost 5672
        '
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - crackhash-net
    restart: unless-stopped

  # Databases

  mongodb:
    image: mongo:7
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: crackhash_db
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: 
        - CMD-SHELL
        - mongosh --quiet -u "$$MONGO_INITDB_ROOT_USERNAME" -p "$$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --eval "db.adminCommand('ping').ok" | grep -q 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - crackhash-net
    restart: unless-stopped


  # Backend

  manager-service:
    build:
      context: ./manager
      dockerfile: Dockerfile
    container_name: manager
    environment:
      MANAGER_PORT: ${MANAGER_PORT}
      WORKERS_COUNT: ${WORKERS_COUNT}
      RABBITMQ_URL: ${RABBITMQ_URL}
      COMB_FOR_TASK: ${COMB_FOR_TASK}
      ERROR_DELAY: ${ERROR_DELAY}
      MONGO_URI: ${MONGODB_URI:-mongodb://admin:password@mongodb:27017/crackhash_db?authSource=admin}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    # depends_on:
    #   manager-db:
    #     condition: service_healthy
    ports:
      - "${MANAGER_PORT}:${INNER_SERVICE_PORT}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - crackhash-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    #healthcheck:
    #  test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${INNER_SERVICE_PORT}/healthz || exit 1"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 10
    #  start_period: 5s

  worker-service:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
    # depends_on:
    #   worker-db:
    #     condition: service_healthy
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - crackhash-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    #healthcheck:
    #  test: ["CMD-SHELL", "wget --spider --quiet http://localhost:${INNER_SERVICE_PORT}/healthz || exit 1"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 10
    #  start_period: 5s

volumes:
  rabbitmq_data:
  mongo_data:

networks:
  crackhash-net:
    driver: bridge
