{
 "title": "Base",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Manager status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "manager_status{job=\"manager\"}"
    }
   ]
  },
  {
   "title": "Worker status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "worker_status{job=\"workers\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Manager rate crack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_class) (\n  rate(manager_requests_total{handler=\"crack\"}[30s])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Manager rate status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_class) (\n  rate(manager_requests_total{handler=\"status\"}[30s])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker tasks count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_tasks_total{job=\"workers\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker active tasks count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "worker_active_tasks{job=\"workers\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker rate success tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(worker_tasks_total{status=\"done\"}[30s]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker rate failed tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(worker_tasks_total{status=\"error\"}[30s]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}