apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    management.tcp.port = 15672
    management.tcp.ip   = 0.0.0.0
    
    default_queue_type = classic
    queue_master_locator = min-masters
    
    log.console = true
    log.console.level = info
    
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.absolute = 1GB